// mc-tunnel — Mission Control Cloud tunnel client.
//
// PROPRIETARY AND CONFIDENTIAL.
// Copyright (c) 2026 Clayrune. All rights reserved.
// Distributed only under the Mission Control Cloud Terms of Service.
//
// Responsibilities (see `02-attestation-protocol.md`):
//   1. Localhost handshake with parent MC process.
//   2. Build & sign attestation envelopes (device key sig from MC + our
//      embedded client secret sig).
//   3. POST attestations to api.PLATFORM_DOMAIN/v1/attest, receive tunnel tokens.
//   4. Run `cloudflared` as a subprocess with the issued token.
//   5. Rotate tokens every 10 minutes; honor server directives.
//
// This is a SKELETON. Every TODO is fleshed out in M2 of `06-rollout-plan.md`.

mod client_secret;     // generated by build.rs — embedded CLIENT_SECRET_PRIV / KEY_ID
mod handshake;
mod attestation;
mod cloudflared;
mod parent_check;

use clap::Parser;
use tracing::{error, info};

#[derive(Parser, Debug)]
#[command(name = "mc-tunnel", version, about = "Mission Control Cloud tunnel client")]
struct Args {
    /// PID of the parent MC process. mc-tunnel exits when this PID dies.
    #[arg(long)]
    mc_pid: u32,

    /// Local Flask port (default 5199; only changed for tests).
    #[arg(long, default_value = "5199")]
    mc_port: u16,

    /// Override control-plane host (staging / dev). Production omits.
    #[arg(long)]
    cp_host: Option<String>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .with_writer(std::io::stderr)
        .init();

    if client_secret::IS_DEV_BUILD {
        error!("This is a DEV build of mc-tunnel. It will NOT be accepted by production control plane. Refusing to run.");
        std::process::exit(2);
    }

    let args = Args::parse();
    info!(?args, "mc-tunnel starting");

    // Read handshake secret from stdin (one line, base64).
    let handshake_secret = handshake::read_secret_from_stdin().await?;

    // Verify parent process matches what we were told.
    if !parent_check::verify(args.mc_pid).await {
        error!("Parent PID mismatch — refusing to start");
        std::process::exit(3);
    }

    // Localhost handshake to MC: prove we have the secret, get challenge etc.
    let session = handshake::call_mc(args.mc_port, &handshake_secret).await?;

    // Main attestation loop: POST /v1/attest every 10 min, run cloudflared
    // with whatever tunnel token comes back.
    attestation::run_loop(session, args.cp_host).await?;

    Ok(())
}
