// build.rs — embeds the per-release client secret at compile time.
//
// PROPRIETARY AND CONFIDENTIAL.
// Copyright (c) 2026 Clayrune. All rights reserved.
//
// Inputs (set by the release pipeline, NEVER committed to source):
//   CLIENT_SECRET_KEY_ID   — e.g. "mc-tunnel-2026a"
//   CLIENT_SECRET_PRIV_HEX — 64 hex chars (32 bytes) of Ed25519 private key seed
//
// Output: src/client_secret.rs containing the constants. Generated at build
// time, overwritten next build, never committed (.gitignore'd).
//
// See `05-build-pipeline.md` §3.1 for the operator workflow.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=CLIENT_SECRET_KEY_ID");
    println!("cargo:rerun-if-env-changed=CLIENT_SECRET_PRIV_HEX");

    let key_id = env::var("CLIENT_SECRET_KEY_ID")
        .unwrap_or_else(|_| {
            // Fallback for `cargo check` / IDE integration. Builds will refuse
            // to ship if the real env vars aren't set — see main.rs runtime check.
            "DEV-NOT-FOR-RELEASE".to_string()
        });

    let priv_hex = env::var("CLIENT_SECRET_PRIV_HEX")
        .unwrap_or_else(|_| "00".repeat(32));

    if priv_hex.len() != 64 {
        panic!("CLIENT_SECRET_PRIV_HEX must be 64 hex chars; got {}", priv_hex.len());
    }

    let mut bytes = [0u8; 32];
    for i in 0..32 {
        bytes[i] = u8::from_str_radix(&priv_hex[i * 2..i * 2 + 2], 16)
            .expect("CLIENT_SECRET_PRIV_HEX must be valid hex");
    }

    let mut byte_literals = String::with_capacity(32 * 6);
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 { byte_literals.push_str(", "); }
        byte_literals.push_str(&format!("0x{:02x}", b));
    }

    let generated = format!(
        "// AUTO-GENERATED by build.rs — DO NOT EDIT, DO NOT COMMIT.\n\
         pub const CLIENT_SECRET_KEY_ID: &str = {key_id:?};\n\
         pub const CLIENT_SECRET_PRIV: [u8; 32] = [{byte_literals}];\n\
         pub const IS_DEV_BUILD: bool = {is_dev};\n",
        key_id = key_id,
        byte_literals = byte_literals,
        is_dev = key_id == "DEV-NOT-FOR-RELEASE",
    );

    let out = Path::new("src").join("client_secret.rs");
    fs::write(&out, generated).expect("could not write client_secret.rs");
}
